server:
  port: 8222
  
eureka:
  client:
    register-with-eureka: false
          
spring:
  application:
    name: gateway  
  cloud:
    gateway:
      routes:
      - id: student
        uri: localhost:8081

#      routes:
#        - id : student
#          uri: http://localhost:8081
#          predicates:
#            - Path= /api/v1/students/** 
#          
#        - id : school
#          uri: http://localhost:8082
#          predicates:
#            - Path= /api/v1/school/** 
#          
#        - id : jwtsecurity
#          uri: http://localhost:8083
#          predicates:
#            - Path= /api/v1/auth/** 

       